"""add scenes

Revision ID: 06750751be41
Revises: 78fb8bb0252f
Create Date: 2023-07-21 23:11:26.316818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06750751be41'
down_revision = '78fb8bb0252f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('path_img', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=100), nullable=True),
    sa.Column('characters', sa.String(length=100), nullable=True),
    sa.Column('path_img', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('windows')
    op.drop_table('scenes')
    # ### end Alembic commands ###
