"""add scenes

Revision ID: 2e097e412e3f
Revises: eb13028e0406
Create Date: 2023-07-23 00:01:50.655206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e097e412e3f'
down_revision = 'eb13028e0406'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('windows', sa.Column('serial_number', sa.Integer(), nullable=True))
    op.add_column('windows', sa.Column('version', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('windows', 'version')
    op.drop_column('windows', 'serial_number')
    # ### end Alembic commands ###
