"""add scenes

Revision ID: 78dee888ccd5
Revises: f442a7ba88b7
Create Date: 2023-07-21 22:33:04.491822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78dee888ccd5'
down_revision = 'f442a7ba88b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
