"""add scenes

Revision ID: 78fb8bb0252f
Revises: ab1883072ebb
Create Date: 2023-07-21 23:07:33.215246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78fb8bb0252f'
down_revision = 'ab1883072ebb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
