"""add scenes

Revision ID: 7cc28a87a940
Revises: 78dee888ccd5
Create Date: 2023-07-21 22:38:37.026181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc28a87a940'
down_revision = '78dee888ccd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
