"""add scenes

Revision ID: 824fe960c575
Revises: 87d656403d9f
Create Date: 2023-07-21 22:59:28.502633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824fe960c575'
down_revision = '87d656403d9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
