"""add scenes

Revision ID: 87d656403d9f
Revises: 7cc28a87a940
Create Date: 2023-07-21 22:42:07.653292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d656403d9f'
down_revision = '7cc28a87a940'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
