"""add scenes

Revision ID: b7cddd82b400
Revises: 06750751be41
Create Date: 2023-07-21 23:36:12.617408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7cddd82b400'
down_revision = '06750751be41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('windows', sa.Column('character', sa.String(length=100), nullable=True))
    op.drop_column('windows', 'characters')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('windows', sa.Column('characters', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('windows', 'character')
    # ### end Alembic commands ###
