"""Database creation

Revision ID: f442a7ba88b7
Revises: 69967f0184a9
Create Date: 2023-07-19 16:22:09.055109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f442a7ba88b7'
down_revision = '69967f0184a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
